<template>
  <usage>
    <template #title>Select</template>
    <template #component>
      <y-select></y-select>
    </template>
  </usage>
  <copy-to-clip-board>
    &lt;y-select&gt; {{ "\n" }} &lt;/y-select&gt;
  </copy-to-clip-board>
  <div class="flex flex-col mt-7 gap-1">
    <p class="font-semibold text-xl">Component Props</p>
    <table>
      <thead>
        <tr>
          <th>Prop Name</th>
          <th>Type</th>
          <th>Default</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>modelValue</td>
          <td>Object,Array,String,Number</td>
          <td></td>
        </tr>
        <tr>
          <td>itemKey</td>
          <td>String</td>
          <td>''</td>
        </tr>
        <tr>
          <td>itemText</td>
          <td>String</td>
          <td>''</td>
        </tr>
        <tr>
          <td>items</td>
          <td>Array,Object,Function</td>
          <td></td>
        </tr>
        <tr>
          <td>fetchResultKey</td>
          <td>String</td>
          <td></td>
        </tr>
        <tr>
          <td>returnObject</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>top</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>left</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>multiple</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>disabled</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>dense</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>chip</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>closeableChip</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>clearAfterSelect</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>helper</td>
          <td>Boolean</td>
          <td>()=>false</td>
        </tr>
        <tr>
          <td>closeAfterSelect</td>
          <td>Boolean</td>
          <td>true</td>
        </tr>
        <tr>
          <td>label</td>
          <td>String</td>
          <td>''</td>
        </tr>
        <tr>
          <td>placeholder</td>
          <td>String</td>
          <td>''</td>
        </tr>
        <tr>
          <td>filter</td>
          <td>Function</td>
          <td></td>
        </tr>
        <tr>
          <td>hint</td>
          <td>String</td>
          <td>''</td>
        </tr>
        <tr>
          <td>disabledText</td>
          <td>String</td>
          <td>''</td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script setup></script>
